import ROOT

ROOT.gROOT.SetBatch(1)
ROOT.gStyle.SetOptTitle(0)
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetHistLineWidth(2)
ROOT.gROOT.ForceStyle()

canvas= ROOT.TCanvas("c","c", 600, 600)
canvas.Draw()

file0=ROOT.TFile.Open("output_Neighbours_20GeV.root","READ")
secondfirstEnFrAsymmetry =file0.Get("secondfirstEnFrAsymmetry")
thirdfirstEnFrAsymmetry  =file0.Get("thirdfirstEnFrAsymmetry")
fourthfirstEnFrAsymmetry =file0.Get("fourthfirstEnFrAsymmetry")
fifthfirstEnFrAsymmetry  =file0.Get("fifthfirstEnFrAsymmetry")
sixthfirstEnFrAsymmetry  =file0.Get("sixthfirstEnFrAsymmetry")
seventhfirstEnFrAsymmetry=file0.Get("seventhfirstEnFrAsymmetry")
eighthfirstEnFrAsymmetry =file0.Get("eighthfirstEnFrAsymmetry")

fileZmm=ROOT.TFile.Open("../../../ZmmAnalyser/ZmmAnalyser/test/output_Neighbours_20GeV.root","READ")
Zmm_secondfirstEnFrAsymmetry =fileZmm.Get("secondfirstEnFrAsymmetry")
Zmm_thirdfirstEnFrAsymmetry  =fileZmm.Get("thirdfirstEnFrAsymmetry")
Zmm_fourthfirstEnFrAsymmetry =fileZmm.Get("fourthfirstEnFrAsymmetry")
Zmm_fifthfirstEnFrAsymmetry  =fileZmm.Get("fifthfirstEnFrAsymmetry")
Zmm_sixthfirstEnFrAsymmetry  =fileZmm.Get("sixthfirstEnFrAsymmetry")
Zmm_seventhfirstEnFrAsymmetry=fileZmm.Get("seventhfirstEnFrAsymmetry")
Zmm_eighthfirstEnFrAsymmetry =fileZmm.Get("eighthfirstEnFrAsymmetry")

canvas.cd()
canvas.SetRightMargin(0.15)

secondfirstEnFrAsymmetry.Scale(1./secondfirstEnFrAsymmetry.Integral())
secondfirstEnFrAsymmetry.Draw("HIST")
secondfirstEnFrAsymmetry.SetLineColor(1)
secondfirstEnFrAsymmetry.GetXaxis().SetTitle("1stE-2ndE / 1stE+2ndE")
Zmm_secondfirstEnFrAsymmetry.Scale(1./Zmm_secondfirstEnFrAsymmetry.Integral())
Zmm_secondfirstEnFrAsymmetry.Draw("HISTSAME")
Zmm_secondfirstEnFrAsymmetry.SetLineColor(2)
mymax=[secondfirstEnFrAsymmetry.GetBinContent(secondfirstEnFrAsymmetry.GetMaximumBin()),Zmm_secondfirstEnFrAsymmetry.GetBinContent(Zmm_secondfirstEnFrAsymmetry.GetMaximumBin()) ]
secondfirstEnFrAsymmetry.GetYaxis().SetRangeUser(0., 1.2*max(mymax))
leg = ROOT.TLegend(0.3, 0.85, 0.75, 0.65)
leg.SetLineColor(0)
leg.SetTextSize(0.05)
leg.SetHeader("2nd - 1st Asymmetry")
leg.AddEntry(secondfirstEnFrAsymmetry, "Z #rightarrow ee", "l")
leg.AddEntry(Zmm_secondfirstEnFrAsymmetry, "Z #rightarrow #mu#mu", "l")
leg.Draw()
canvas.SaveAs("plots/secondfirstEnAsymmetry.png")
canvas.SaveAs("plots/secondfirstEnAsymmetry.pdf")

canvas.Clear()
thirdfirstEnFrAsymmetry.Scale(1./thirdfirstEnFrAsymmetry.Integral())
thirdfirstEnFrAsymmetry.Draw("HIST")
thirdfirstEnFrAsymmetry.SetLineColor(1)
thirdfirstEnFrAsymmetry.GetXaxis().SetTitle("1stE-3rdE / 1stE+3rdE")
Zmm_thirdfirstEnFrAsymmetry.Scale(1./Zmm_thirdfirstEnFrAsymmetry.Integral())
Zmm_thirdfirstEnFrAsymmetry.Draw("HISTSAME")
Zmm_thirdfirstEnFrAsymmetry.SetLineColor(2)
mymax=[thirdfirstEnFrAsymmetry.GetBinContent(thirdfirstEnFrAsymmetry.GetMaximumBin()),Zmm_thirdfirstEnFrAsymmetry.GetBinContent(Zmm_thirdfirstEnFrAsymmetry.GetMaximumBin()) ]
thirdfirstEnFrAsymmetry.GetYaxis().SetRangeUser(0., 1.2*max(mymax))
leg.Clear()
leg.SetHeader("3rd - 1st Asymmetry")
leg.AddEntry(thirdfirstEnFrAsymmetry, "Z #rightarrow ee", "l")
leg.AddEntry(Zmm_thirdfirstEnFrAsymmetry, "Z #rightarrow #mu#mu", "l")
leg.Draw()
canvas.SaveAs("plots/thirdfirstEnAsymmetry.png")
canvas.SaveAs("plots/thirdfirstEnAsymmetry.pdf")


canvas.Clear()
fourthfirstEnFrAsymmetry.Scale(1./fourthfirstEnFrAsymmetry.Integral())
fourthfirstEnFrAsymmetry.Draw("HIST")
fourthfirstEnFrAsymmetry.SetLineColor(1)
fourthfirstEnFrAsymmetry.GetXaxis().SetTitle("1stE-4thE / 1stE+4thE")
Zmm_fourthfirstEnFrAsymmetry.Scale(1./Zmm_fourthfirstEnFrAsymmetry.Integral())
Zmm_fourthfirstEnFrAsymmetry.Draw("HISTSAME")
Zmm_fourthfirstEnFrAsymmetry.SetLineColor(2)
mymax=[fourthfirstEnFrAsymmetry.GetBinContent(fourthfirstEnFrAsymmetry.GetMaximumBin()),Zmm_fourthfirstEnFrAsymmetry.GetBinContent(Zmm_fourthfirstEnFrAsymmetry.GetMaximumBin()) ]
fourthfirstEnFrAsymmetry.GetYaxis().SetRangeUser(0., 1.2*max(mymax))
leg.Clear()
leg.SetHeader("4th - 1st Asymmetry")
leg.AddEntry(fourthfirstEnFrAsymmetry, "Z #rightarrow ee", "l")
leg.AddEntry(Zmm_fourthfirstEnFrAsymmetry, "Z #rightarrow #mu#mu", "l")
leg.Draw()
canvas.SaveAs("plots/fourthfirstEnAsymmetry.png")
canvas.SaveAs("plots/fourthfirstEnAsymmetry.pdf")

canvas.Clear()
fifthfirstEnFrAsymmetry.Scale(1./fifthfirstEnFrAsymmetry.Integral())
fifthfirstEnFrAsymmetry.Draw("HIST")
fifthfirstEnFrAsymmetry.SetLineColor(1)
fifthfirstEnFrAsymmetry.GetXaxis().SetTitle("1stE-5thE / 1stE+5thE")
Zmm_fifthfirstEnFrAsymmetry.Scale(1./Zmm_fifthfirstEnFrAsymmetry.Integral())
Zmm_fifthfirstEnFrAsymmetry.Draw("HISTSAME")
Zmm_fifthfirstEnFrAsymmetry.SetLineColor(2)
mymax=[fifthfirstEnFrAsymmetry.GetBinContent(fifthfirstEnFrAsymmetry.GetMaximumBin()),Zmm_fifthfirstEnFrAsymmetry.GetBinContent(Zmm_fifthfirstEnFrAsymmetry.GetMaximumBin()) ]
fifthfirstEnFrAsymmetry.GetYaxis().SetRangeUser(0., 1.2*max(mymax))
leg.Clear()
leg.SetHeader("5th - 1st Asymmetry")
leg.AddEntry(fifthfirstEnFrAsymmetry, "Z #rightarrow ee", "l")
leg.AddEntry(Zmm_fifthfirstEnFrAsymmetry, "Z #rightarrow #mu#mu", "l")
leg.Draw()
canvas.SaveAs("plots/fifthfirstEnAsymmetry.png")
canvas.SaveAs("plots/fifthfirstEnAsymmetry.pdf")

canvas.Clear()
sixthfirstEnFrAsymmetry.Scale(1./sixthfirstEnFrAsymmetry.Integral())
sixthfirstEnFrAsymmetry.Draw("HIST")
sixthfirstEnFrAsymmetry.SetLineColor(1)
sixthfirstEnFrAsymmetry.GetXaxis().SetTitle("1stE-6thE / 1stE+6thE")
Zmm_sixthfirstEnFrAsymmetry.Scale(1./Zmm_sixthfirstEnFrAsymmetry.Integral())
Zmm_sixthfirstEnFrAsymmetry.Draw("HISTSAME")
Zmm_sixthfirstEnFrAsymmetry.SetLineColor(2)
mymax=[sixthfirstEnFrAsymmetry.GetBinContent(sixthfirstEnFrAsymmetry.GetMaximumBin()),Zmm_sixthfirstEnFrAsymmetry.GetBinContent(Zmm_sixthfirstEnFrAsymmetry.GetMaximumBin()) ]
sixthfirstEnFrAsymmetry.GetYaxis().SetRangeUser(0., 1.2*max(mymax))
leg.Clear()
leg.SetHeader("6th - 1st Asymmetry")
leg.AddEntry(sixthfirstEnFrAsymmetry, "Z #rightarrow ee", "l")
leg.AddEntry(Zmm_sixthfirstEnFrAsymmetry, "Z #rightarrow #mu#mu", "l")
leg.Draw()
canvas.SaveAs("plots/sixthfirstEnAsymmetry.png")
canvas.SaveAs("plots/sixthfirstEnAsymmetry.pdf")

canvas.Clear()
seventhfirstEnFrAsymmetry.Scale(1./seventhfirstEnFrAsymmetry.Integral())
seventhfirstEnFrAsymmetry.Draw("HIST")
seventhfirstEnFrAsymmetry.SetLineColor(1)
seventhfirstEnFrAsymmetry.GetXaxis().SetTitle("1stE-7thE / 1stE+7thE")
Zmm_seventhfirstEnFrAsymmetry.Scale(1./Zmm_seventhfirstEnFrAsymmetry.Integral())
Zmm_seventhfirstEnFrAsymmetry.Draw("HISTSAME")
Zmm_seventhfirstEnFrAsymmetry.SetLineColor(2)
mymax=[seventhfirstEnFrAsymmetry.GetBinContent(seventhfirstEnFrAsymmetry.GetMaximumBin()),Zmm_seventhfirstEnFrAsymmetry.GetBinContent(Zmm_seventhfirstEnFrAsymmetry.GetMaximumBin()) ]
seventhfirstEnFrAsymmetry.GetYaxis().SetRangeUser(0., 1.2*max(mymax))
leg.Clear()
leg.SetHeader("7th - 1st Asymmetry")
leg.AddEntry(seventhfirstEnFrAsymmetry, "Z #rightarrow ee", "l")
leg.AddEntry(Zmm_seventhfirstEnFrAsymmetry, "Z #rightarrow #mu#mu", "l")
leg.Draw()
canvas.SaveAs("plots/seventhfirstEnAsymmetry.png")
canvas.SaveAs("plots/seventhfirstEnAsymmetry.pdf")

canvas.Clear()
eighthfirstEnFrAsymmetry.Scale(1./eighthfirstEnFrAsymmetry.Integral())
eighthfirstEnFrAsymmetry.Draw("HIST")
eighthfirstEnFrAsymmetry.SetLineColor(1)
eighthfirstEnFrAsymmetry.GetXaxis().SetTitle("1stE-8thE / 1stE+8thE")
Zmm_eighthfirstEnFrAsymmetry.Scale(1./Zmm_eighthfirstEnFrAsymmetry.Integral())
Zmm_eighthfirstEnFrAsymmetry.Draw("HISTSAME")
Zmm_eighthfirstEnFrAsymmetry.SetLineColor(2)
mymax=[eighthfirstEnFrAsymmetry.GetBinContent(eighthfirstEnFrAsymmetry.GetMaximumBin()),Zmm_eighthfirstEnFrAsymmetry.GetBinContent(Zmm_eighthfirstEnFrAsymmetry.GetMaximumBin()) ]
eighthfirstEnFrAsymmetry.GetYaxis().SetRangeUser(0., 1.2*max(mymax))
leg.Clear()
leg.SetHeader("8th - 1st Asymmetry")
leg.AddEntry(eighthfirstEnFrAsymmetry, "Z #rightarrow ee", "l")
leg.AddEntry(Zmm_eighthfirstEnFrAsymmetry, "Z #rightarrow #mu#mu", "l")
leg.Draw()
canvas.SaveAs("plots/eighthfirstEnAsymmetry.png")
canvas.SaveAs("plots/eighthfirstEnAsymmetry.pdf")


file0.Close()
fileZmm.Close()
